//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp
    {
        public int Id_Group { get; set; }
        public int Id_Stud { get; set; }
        public int Id_temp { get; set; }
        public int Id_Org { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Organizat Organizat { get; set; }
        public virtual Sotrudnick Sotrudnick { get; set; }
    }
}
